<?php
return	array (
  'signName' => '',
  'templateCode' => '',
  'accessKeyId' => '',
  'accessKeySecret' => '',
  'tempid' => '',
  'appkey' => '',
  'sign' => '',
  'server' => '',
  'partner' => '',
  'key' => '',
  'notify_url' => '',
  'return_url' => '',
  'sitename' => '',
  'smtpHost' => '',
  'smtpPort' => '',
  'smtpAccount' => '',
  'smtpPassword' => '',
  'smtpSendEmail' => '',
  'smtpSendName' => '',
  'systemName' => '',
  'systemUrl' => '',
  'systemCopy' => '',
  'myFile' => '',
);